### ISSUE TITLE
where i can find secret_key 

### ISSUE THREAD

**Issue by satya5561** [ransom1538/amazon-gift-cards-sdk-php#1]
$this->secret_key = [YOUR SECRET KEY HERE];

please send me url so than i will create secret_key

**Comment by ransom1538** [comment]
Yes, you just call amazon create an account with them, they will mail the information. It isn't self serve. 
https://www.amazon.com/b?node=15243199011
Contact would lead you to: 
http://www.amazon-incentives.com/us/contactincentives
